### ISSUE TITLE
where is the paper？

### ISSUE THREAD

**Issue by qiongxiao** [gusgad/capsule-GAN#4]
Hello，where can see  your Master thesis of “Capsule Layer as a Discriminator in Generative Adversarial Networks“ ? I can't  find it on the web by baidu or google,can you send it to my Email of  xqlily@live.cn ?thanks very much!

**Comment by gusgad** [comment]
Hi @qiongxiao! Unfortunately I'm still working on it and due to a tight schedule it takes time to document it all. In the meantime, you can check the recent paper on the same topic: https://arxiv.org/abs/1802.06167

**Comment by qiongxiao** [comment]
thanks very much！

**Comment by cbsudux** [comment]
Hi, @gusgad ,is https://arxiv.org/abs/1802.06167 your paper?

**Comment by gusgad** [comment]
HI @cbsudux! No, it's not mine. I couldn't find the code of those guys either.

**Comment by cbsudux** [comment]
Sure alright
